var searchData=
[
  ['chip_20chip_20errata_20workarounds_0',['CHIP - Chip Errata Workarounds',['../group__chip.html',1,'']]],
  ['chip_20errata_20workarounds_1',['CHIP - Chip Errata Workarounds',['../group__chip.html',1,'']]],
  ['clock_20initialization_2',['Clock Initialization',['../group__device__init__clocks.html',1,'']]],
  ['cmsis_20core_20instruction_20interface_3',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions_4',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['cmsis_20global_20defines_5',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['cmsis_20simd_20intrinsics_6',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['codes_7',['EFM32GG990F1024 Unlock Codes',['../group___e_f_m32_g_g990_f1024___u_n_l_o_c_k.html',1,'']]],
  ['common_20common_20utilities_8',['COMMON - Common Utilities',['../group__common.html',1,'']]],
  ['common_20utilities_9',['COMMON - Common Utilities',['../group__common.html',1,'']]],
  ['control_10',['Board Control',['../group__board__control.html',1,'']]],
  ['control_20block_20scb_11',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['control_20registers_12',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['controller_20nvic_13',['Nested Vectored Interrupt Controller (NVIC)',['../group___c_m_s_i_s___n_v_i_c.html',1,'']]],
  ['controls_20not_20in_20scb_20scnscb_14',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['core_15',['EFM32GG990F1024 Core',['../group___e_f_m32_g_g990_f1024___core.html',1,'']]],
  ['core_20core_20interrupt_16',['CORE - Core Interrupt',['../group__core.html',1,'']]],
  ['core_20debug_20registers_20coredebug_17',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['core_20definitions_18',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['core_20instruction_20interface_19',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['core_20interrupt_20',['CORE - Core Interrupt',['../group__core.html',1,'']]],
  ['core_20register_20access_20functions_21',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['core_20register_20bit_20field_20macros_22',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['coredebug_23',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]]
];
